version: "3.9"
services:
  web:
    build:
      context: ./MbtiPredictorGUI
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8000:80"
    environment:
      - API_URL=http://predictor:12000/
  predictor:
    build:
      context: MbtiPredictorApi
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
